<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ascii_table</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>ASCII Table</string>
	<key>hidden</key>
	<true/>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.label.ascii_table</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.label.ascii_table</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.label.ascii_table</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.function.label.ascii_table</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.function.label.ascii_table</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.function.label.ascii_table</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(DEC) +(HEX) +(OCT) +(CHR) +(HTML) +(DESCRIPTION)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal.ascii_table</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hex.ascii_table</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.octal.ascii_table</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.char.ascii_table</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.type.ascii_table</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.info.ascii_table</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^ *(\d+) +(0x[\da-fA-F]+) +(0o[0-8]+) +([^ ]+)(?: +(&amp;[A-Za-z\d]+;))?(?: +(\(.*\)))?$</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ascii_table</string>
	<key>uuid</key>
	<string>300cbd58-baf4-4476-9923-72fb67ec0170</string>
</dict>
</plist>
