site_name: Sublime Random Crap Documentation
repo_url: https://github.com/facelessuser/SublimeRandomCrap
site_description: Random plugins and scripts for Sublime Text.
copyright: Copyright &copy; 2011 - 2015 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
- ['index.md', 'Home']
- ['asciitable.md', 'Plugins', 'AsciiTable']
- ['grephere.md', 'Plugins', 'GrepHere']
- ['highlightword.md', 'Plugins', 'HighlightWord']
- ['insertdate.md', 'Plugins', 'InsertDate']
- ['postmaster.md', 'Plugins', 'Postmaster']
- ['shortcutplus.md', 'Plugins', 'ShortcutPlus']
- ['sublimeapidoc.md', 'Plugins', 'SublimeApiDoc']
- ['sublimeinfo.md', 'Plugins', 'SublimeInfo']
- ['togglewhitespace.md', 'Plugins', 'ToggleWhiteSpace']
- ['license.md', 'License']
theme: readthedocs
extra_javascript:
- js/theme_custom.js
extra_css:
- css/theme_custom.css
markdown_extensions:
- markdown.extensions.extra
- markdown.extensions.admonition
- markdown.extensions.smarty
- markdown.extensions.nl2br
- pymdownx.inlinehilite(use_pygments=False)
- pymdownx.magiclink
- pymdownx.betterem
- pymdownx.tilde
- pymdownx.caret
- pymdownx.smartsymbols
- pymdownx.githubemoji
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.progressbar
