site_name: Sublime Random Crap Documentation
site_url: https://facelessuser.github.io/SublimeRandomCrap
repo_url: https://github.com/facelessuser/SublimeRandomCrap
edit_uri: tree/master/docs/src/markdown
site_description: Random plugins and scripts for Sublime Text.
copyright: |
  Copyright &copy; 2011 - 2019 <a href="https://github.com/facelessuser">Isaac Muse</a>
  <br><span class="md-footer-custom-text">emoji provided free by </span>
  <a href="https://github.com/twitter/twemoji">Twemoji</a>

docs_dir: docs/src/markdown
theme:
  name: material
  custom_dir: docs/theme
  palette:
    primary: blue
    accent: blue
  logo:
    icon: description
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Plugins:
    - AsciiTable: plugins/asciitable.md
    - HighlightWord: plugins/highlightword.md
    - ShortcutPlus: plugins/shortcutplus.md
    - SublimeApiDoc: plugins/sublimeapidoc.md
    - SublimeInfo: plugins/sublimeinfo.md
    - ToggleWhiteSpace: plugins/togglewhitespace.md
    - AutoSideBar: plugins/autosidebar.md
    - URLOpen: plugins/urlopen.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\ue157"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      user: facelessuser
      repo: SublimeRandomCrap
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

extra:
  social:
    - type: github
      link: https://github.com/facelessuser
extra_css:
  - extra-174a536342.css
extra_javascript:
  - extra-0d9305e748.js
